  version: '3.8'

  services:
    app:
      image: 'docker-spring-boot-postgres:latest'
      build:
        context: .
      container_name: app
      depends_on:
        - db
      env_file:
        - .env
      ports:
        - "${APP_PORT}:${CONTAINER_PORT}"

    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "${DB_PORT}:${DB_CONTAINER_PORT}"
